{"name":"Customer Support Bridge","description":"","version":"1.0","culture":"en-GB","modifiedTime":"2024-04-20T14:14:47.3189059+00:00","ppdf:outputFileFormat":"csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"skipAutomaticHeaderAndTypeDetection":false,"queriesMetadata":{"RECEIVED_PAYLOAD":{"queryId":"18fbb3c0-47a2-427d-aa7b-8eb72bcf720a","queryName":"RECEIVED_PAYLOAD","loadEnabled":true},"WORKER":{"queryId":"9c8c470b-dd78-4b97-8009-9b45ceb0c0c0","queryName":"WORKER","loadEnabled":true},"WORKER_LOG":{"queryId":"098bba5c-dbaf-4a72-9ac5-ea258d2918e4","queryName":"WORKER_LOG","loadEnabled":true}},"document":"section Section1;\r\nshared RECEIVED_PAYLOAD = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"CUSTOMER_SUPPORT_BRIDGE_STATUS\", Item = \"RECEIVED_PAYLOAD\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(#\"Navigation 1\", Table.ColumnsOfType(#\"Navigation 1\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\nshared WORKER = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"CUSTOMER_SUPPORT_BRIDGE_STATUS\", Item = \"WORKER\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(#\"Navigation 1\", Table.ColumnsOfType(#\"Navigation 1\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\nshared WORKER_LOG = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"CUSTOMER_SUPPORT_BRIDGE_STATUS\", Item = \"WORKER_LOG\"]}[Data],\r\n  #\"Remove columns\" = Table.RemoveColumns(#\"Navigation 1\", Table.ColumnsOfType(#\"Navigation 1\", {type table, type record, type list, type nullable binary, type binary, type function}))\r\nin\r\n  #\"Remove columns\";\r\n","connectionOverrides":[{"path":"aws-0-eu-central-1.pooler.supabase.com;postgres","kind":"PostgreSQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"PostgreSQL\",\"path\":\"aws-0-eu-central-1.pooler.supabase.com;postgres\"}","audience":null},{"path":"linksoft-crm.crm4.dynamics.com","kind":"CommonDataService","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"CommonDataService\",\"path\":\"linksoft-crm.crm4.dynamics.com\"}","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"RECEIVED_PAYLOAD","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"RECEIVED_PAYLOAD.csv"},"attributes":[{"name":"created_at","dataType":"dateTime"},{"name":"external_reference_id","dataType":"string"},{"name":"external_payload","dataType":"string"},{"name":"status","dataType":"string"},{"name":"worker","dataType":"string"},{"name":"id","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T14:15:33.2947329+00:00","location":"https://wabiweubpcdsa.blob.core.windows.net:443/04e9eeaa-b52e-4c3c-82e6-74ab973cb88d/RECEIVED_PAYLOAD.csv?snapshot=2024-04-20T14%3A15%3A33.2877902Z"}]},{"$type":"LocalEntity","name":"WORKER","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WORKER.csv"},"attributes":[{"name":"id","dataType":"string"},{"name":"created_at","dataType":"dateTime"},{"name":"worker_status","dataType":"string"},{"name":"worker_type","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T14:16:03.5765916+00:00","location":"https://wabiweubpcdsa.blob.core.windows.net:443/04e9eeaa-b52e-4c3c-82e6-74ab973cb88d/WORKER.csv?snapshot=2024-04-20T14%3A16%3A03.5681006Z"}]},{"$type":"LocalEntity","name":"WORKER_LOG","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"WORKER_LOG.csv"},"attributes":[{"name":"id","dataType":"string"},{"name":"created_at","dataType":"dateTime"},{"name":"worker","dataType":"string"},{"name":"received_payload","dataType":"string"},{"name":"type","dataType":"string"},{"name":"subtype","dataType":"string"},{"name":"information","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T14:16:33.8740781+00:00","location":"https://wabiweubpcdsa.blob.core.windows.net:443/04e9eeaa-b52e-4c3c-82e6-74ab973cb88d/WORKER_LOG.csv?snapshot=2024-04-20T14%3A16%3A33.8764083Z"}]}],"relationships":[{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"RECEIVED_PAYLOAD","attributeName":"id"},"toAttribute":{"entityName":"WORKER_LOG","attributeName":"received_payload"}},{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"WORKER","attributeName":"id"},"toAttribute":{"entityName":"RECEIVED_PAYLOAD","attributeName":"worker"}},{"$type":"SingleKeyRelationship","fromAttribute":{"entityName":"WORKER","attributeName":"id"},"toAttribute":{"entityName":"WORKER_LOG","attributeName":"worker"}}]}