{"name":"Power Query Exercises","description":"","version":"1.0","culture":"en-GB","modifiedTime":"2024-04-20T10:37:47.6987168+00:00","ppdf:outputFileFormat":"csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"skipAutomaticHeaderAndTypeDetection":false,"queriesMetadata":{"Type casting":{"queryId":"9036e898-9871-428c-b9f7-c3cf2be486b9","queryName":"Type casting","queryGroupId":"ae5fc2e2-0e35-4744-846d-c4964261e147","loadEnabled":true},"Delimiter separated values":{"queryId":"f36bd829-68be-48fc-8836-6b459783d1a8","queryName":"Delimiter separated values","queryGroupId":"e254aa64-c995-446f-a00b-3725fa9d53c5","loadEnabled":true},"Schema changes":{"queryId":"0c9084b4-2ded-4441-aab3-2df5a97f1515","queryName":"Schema changes","queryGroupId":"2e3ca2c1-91bc-4dd5-9b0d-ff6ea8fd4e57","loadEnabled":true},"Left table":{"queryId":"fbdc240f-a4d0-4721-9107-128a73706294","queryName":"Left table","queryGroupId":"efa7e860-7e33-496b-b3ff-433cfe7a6e3f","loadEnabled":true},"Right table":{"queryId":"75db812e-e3cb-4c3b-9293-3d5bd42fe292","queryName":"Right table","queryGroupId":"efa7e860-7e33-496b-b3ff-433cfe7a6e3f","loadEnabled":true},"Non scalar power query types":{"queryId":"69b3aa19-fd3c-4a44-ba80-882a249bc0c9","queryName":"Non scalar power query types","queryGroupId":"87457bf0-ac2e-482e-948a-5ae1a33e52b7","loadEnabled":true},"PARAMETER__YEAR":{"queryId":"50ca4e85-087d-4a28-9eea-c9111f020c5a","queryName":"PARAMETER__YEAR","queryGroupId":"0e8cd78c-c49a-4f69-8252-3ea2892189df"},"Year":{"queryId":"cee2152c-526a-440e-9630-1725b32ef0e1","queryName":"Year","queryGroupId":"0e8cd78c-c49a-4f69-8252-3ea2892189df"},"Table affected by parameters":{"queryId":"8ddc516c-744a-48a9-b3cf-dc2d91bf4fe3","queryName":"Table affected by parameters","queryGroupId":"0e8cd78c-c49a-4f69-8252-3ea2892189df","loadEnabled":true},"Schema":{"queryId":"92c7fc0a-4963-4b66-b2e0-27b7d0294e66","queryName":"Schema","queryGroupId":"0e8cd78c-c49a-4f69-8252-3ea2892189df"},"a_user_defined_function":{"queryId":"584b403c-da05-4b76-a5fe-d74f20da8d0d","queryName":"a_user_defined_function","queryGroupId":"0905ed1f-58d6-4cb0-a438-5ea470ae9888"},"Function showcase":{"queryId":"f3cc26c9-7c07-4cc3-849e-a6d4af051ffa","queryName":"Function showcase","queryGroupId":"0905ed1f-58d6-4cb0-a438-5ea470ae9888","loadEnabled":true},"Showcase for the M syntax":{"queryId":"4bdbcb82-b7b3-4a56-a235-54329ecbbde3","queryName":"Showcase for the M syntax","queryGroupId":"3e9cab24-314a-4797-a87a-c6be25d12e1d","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Type casting\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__INTEGER_AS_VARCHAR\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared #\"Delimiter separated values\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__DELIMITER_SEPARATED_VALUES\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared #\"Schema changes\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__SCHEMA_CHANGES\"]}[Data],\r\n  #\"Unpivoted other columns\" = Table.UnpivotOtherColumns(#\"Navigation 1\", {\"ID\"}, \"Attribute\", \"Value\")\r\nin\r\n  #\"Unpivoted other columns\";\r\nshared #\"Left table\" = let\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__JOIN_LEFT_TABLE\"]}[Data]\nin\n  #\"Navigation 1\";\r\nshared #\"Right table\" = let\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__JOIN_RIGHT_TABLE\"]}[Data]\nin\n  #\"Navigation 1\";\r\nshared #\"Non scalar power query types\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__NON_SCALAR_TYPES\"]}[Data],\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Navigation 1\", {{\"JSON_TYPE\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"JSON_TYPE\", null}})\r\nin\r\n  #\"Replace errors\";\r\nshared PARAMETER__YEAR = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"HELPER_TABLE__PARAMETERS\"]}[Data],\r\n  #\"Removed other columns\" = Table.SelectColumns(#\"Navigation 1\", {\"PARAMETER__YEAR\"}),\r\n  #\"Changed column type\" = Table.TransformColumnTypes(#\"Removed other columns\", {{\"PARAMETER__YEAR\", type text}}),\r\n  Custom = Table.ToList(#\"Changed column type\")\r\nin\r\n  Custom;\r\nshared Year = 2022 meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type number, ExpressionIdentifier = PARAMETER__YEAR];\r\nshared #\"Table affected by parameters\" = let\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\n  #\"Navigation 1\" = Source{[Schema = Schema, Item = \"EXERCISE_TABLE__PARAMETERS\"]}[Data],\n  #\"Filtered rows\" = Table.SelectRows(#\"Navigation 1\", each [YEAR] = Year)\nin\n  #\"Filtered rows\";\r\nshared Schema = \"THE_OTHER_POWER_QUERY_EXERCISES\" meta [IsParameterQuery = true, IsParameterQueryRequired = true, Type = type text, List = {\"THE_OTHER_POWER_QUERY_EXERCISES\", \"POWER_QUERY_EXERCISES\"}];\r\nshared a_user_defined_function = (TEXT_PARAMETER as text, NUMERIC_PARAMETER as number) as text => \nlet\n  result = \"TEXT_PARAMETER=\" & TEXT_PARAMETER & \"; NUMERIC_PARAMTER=\" & Text.From(NUMERIC_PARAMETER)\nin\n  result;\r\nshared #\"Function showcase\" = let\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"HELPER_TABLE__USER_DEFINED_FUNCTIONS\"]}[Data]\nin\n  #\"Navigation 1\";\r\nshared #\"Showcase for the M syntax\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  // This is a comment\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__SCHEMA_CHANGES\"]}[Data],\r\n  #\"Renamed columns\" = Table.RenameColumns(#\"Navigation 1\", {{\"2022\", \"2022_YTD\"}, {\"2021\", \"2021_EOY\"}}),\r\n  #\"Replaced value\" = Table.ReplaceValue(#\"Renamed columns\", 20, 15, Replacer.ReplaceValue, {\"2020\"}),\r\n  #\"Added custom\" = Table.AddColumn(#\"Replaced value\", \"2023_YTD\", each [2022_YTD] + .25 * [2022_YTD]),\r\n  #\"Renamed columns 1\" = Table.RenameColumns(#\"Added custom\", {{\"2022_YTD\", \"2022_EOY\"}}),\r\n  #\"Unpivoted other columns\" = Table.UnpivotOtherColumns(#\"Renamed columns 1\", {\"ID\"}, \"Attribute\", \"Value\"),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Unpivoted other columns\", {{\"Value\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Value\", null}})\r\nin\r\n  #\"Replace errors\";\r\n","connectionOverrides":[{"path":"PowerPlatformDataflows","kind":"PowerPlatformDataflows","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"PowerPlatformDataflows\",\"path\":\"PowerPlatformDataflows\"}","audience":null},{"path":"linksoft-crm.crm4.dynamics.com","kind":"CommonDataService","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"CommonDataService\",\"path\":\"linksoft-crm.crm4.dynamics.com\"}","audience":null},{"path":"aws-0-eu-central-1.pooler.supabase.com;postgres","kind":"PostgreSQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"PostgreSQL\",\"path\":\"aws-0-eu-central-1.pooler.supabase.com;postgres\"}","audience":null},{"path":"https://www.dataaccess.com/webservicesserver/numberconversion.wso","kind":"Web","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Web\",\"path\":\"https://www.dataaccess.com/webservicesserver/numberconversion.wso\"}","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"ae5fc2e2-0e35-4744-846d-c4964261e147\",\"name\":\"Data types\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"e254aa64-c995-446f-a00b-3725fa9d53c5\",\"name\":\"Data Transformation\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"2e3ca2c1-91bc-4dd5-9b0d-ff6ea8fd4e57\",\"name\":\"Schema changes\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"efa7e860-7e33-496b-b3ff-433cfe7a6e3f\",\"name\":\"Joins\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"87457bf0-ac2e-482e-948a-5ae1a33e52b7\",\"name\":\"Non scalar data types\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"0e8cd78c-c49a-4f69-8252-3ea2892189df\",\"name\":\"Parameters\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"0905ed1f-58d6-4cb0-a438-5ea470ae9888\",\"name\":\"User defined functions\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"3e9cab24-314a-4797-a87a-c6be25d12e1d\",\"name\":\"Query syntax\",\"description\":\"\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"Type casting","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Type%20casting.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"INTEGER_AS_VARCHAR","dataType":"string"},{"name":"DATE_AS_VARCHAR","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:38:20.8749345+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Type%2520casting.csv?snapshot=2024-04-20T10%3A38%3A20.8788579Z"}]},{"$type":"LocalEntity","name":"Delimiter separated values","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Delimiter%20separated%20values.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"DELIMITER_SEPARATED_VALUES","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:38:51.1960819+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Delimiter%2520separated%2520values.csv?snapshot=2024-04-20T10%3A38%3A51.1982154Z"}]},{"$type":"LocalEntity","name":"Schema changes","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Schema%20changes.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"Attribute","dataType":"string"},{"name":"Value","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:39:21.4640314+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Schema%2520changes.csv?snapshot=2024-04-20T10%3A39%3A21.4546103Z"}]},{"$type":"LocalEntity","name":"Left table","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Left%20table.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"REFERENCE__JOIN_LEFT_TABLE","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:39:51.7536696+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Left%2520table.csv?snapshot=2024-04-20T10%3A39%3A51.7559792Z"}]},{"$type":"LocalEntity","name":"Right table","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Right%20table.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"LABEL","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:40:22.020839+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Right%2520table.csv?snapshot=2024-04-20T10%3A40%3A22.0163736Z"}]},{"$type":"LocalEntity","name":"Non scalar power query types","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Non%20scalar%20power%20query%20types.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"JSON_TYPE","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:40:52.4447867+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Non%2520scalar%2520power%2520query%2520types.csv?snapshot=2024-04-20T10%3A40%3A52.4456715Z"}]},{"$type":"LocalEntity","name":"Table affected by parameters","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Table%20affected%20by%20parameters.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"YEAR","dataType":"int64"},{"name":"VALUE","dataType":"double"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:41:22.7288076+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Table%2520affected%2520by%2520parameters.csv?snapshot=2024-04-20T10%3A41%3A22.7300530Z"}]},{"$type":"LocalEntity","name":"Function showcase","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Function%20showcase.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"TEXT","dataType":"string"},{"name":"NUMBER","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:41:52.9973137+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Function%2520showcase.csv?snapshot=2024-04-20T10%3A41%3A52.9984439Z"}]},{"$type":"LocalEntity","name":"Showcase for the M syntax","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Showcase%20for%20the%20M%20syntax.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"Attribute","dataType":"string"},{"name":"Value","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-20T10:42:23.2987998+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Showcase%2520for%2520the%2520M%2520syntax.csv?snapshot=2024-04-20T10%3A42%3A23.3038133Z"}]}]}