{"name":"Power Query Exercises","description":"","version":"1.0","culture":"en-GB","modifiedTime":"2024-04-15T20:04:47.3429494+00:00","ppdf:outputFileFormat":"csv","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"skipAutomaticHeaderAndTypeDetection":false,"queriesMetadata":{"Type casting":{"queryId":"9036e898-9871-428c-b9f7-c3cf2be486b9","queryName":"Type casting","queryGroupId":"ae5fc2e2-0e35-4744-846d-c4964261e147","loadEnabled":true},"Delimiter separated values":{"queryId":"f36bd829-68be-48fc-8836-6b459783d1a8","queryName":"Delimiter separated values","queryGroupId":"e254aa64-c995-446f-a00b-3725fa9d53c5","loadEnabled":true},"Schema changes":{"queryId":"0c9084b4-2ded-4441-aab3-2df5a97f1515","queryName":"Schema changes","queryGroupId":"2e3ca2c1-91bc-4dd5-9b0d-ff6ea8fd4e57","loadEnabled":true},"Left table":{"queryId":"fbdc240f-a4d0-4721-9107-128a73706294","queryName":"Left table","queryGroupId":"efa7e860-7e33-496b-b3ff-433cfe7a6e3f","loadEnabled":true},"Right table":{"queryId":"75db812e-e3cb-4c3b-9293-3d5bd42fe292","queryName":"Right table","queryGroupId":"efa7e860-7e33-496b-b3ff-433cfe7a6e3f","loadEnabled":true},"Non scalar power query types":{"queryId":"69b3aa19-fd3c-4a44-ba80-882a249bc0c9","queryName":"Non scalar power query types","queryGroupId":"87457bf0-ac2e-482e-948a-5ae1a33e52b7","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Type casting\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__INTEGER_AS_VARCHAR\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared #\"Delimiter separated values\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__DELIMITER_SEPARATED_VALUES\"]}[Data]\r\nin\r\n  #\"Navigation 1\";\r\nshared #\"Schema changes\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__SCHEMA_CHANGES\"]}[Data],\r\n  #\"Unpivoted other columns\" = Table.UnpivotOtherColumns(#\"Navigation 1\", {\"ID\"}, \"Attribute\", \"Value\")\r\nin\r\n  #\"Unpivoted other columns\";\r\nshared #\"Left table\" = let\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__JOIN_LEFT_TABLE\"]}[Data]\nin\n  #\"Navigation 1\";\r\nshared #\"Right table\" = let\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__JOIN_RIGHT_TABLE\"]}[Data]\nin\n  #\"Navigation 1\";\r\nshared #\"Non scalar power query types\" = let\r\n  Source = PostgreSQL.Database(\"aws-0-eu-central-1.pooler.supabase.com\", \"postgres\"),\r\n  #\"Navigation 1\" = Source{[Schema = \"POWER_QUERY_EXERCISES\", Item = \"EXERCISE_TABLE__NON_SCALAR_TYPES\"]}[Data],\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Navigation 1\", {{\"JSON_TYPE\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"JSON_TYPE\", null}})\r\nin\r\n  #\"Replace errors\";\r\n","connectionOverrides":[{"path":"PowerPlatformDataflows","kind":"PowerPlatformDataflows","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"PowerPlatformDataflows\",\"path\":\"PowerPlatformDataflows\"}","audience":null},{"path":"linksoft-crm.crm4.dynamics.com","kind":"CommonDataService","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"CommonDataService\",\"path\":\"linksoft-crm.crm4.dynamics.com\"}","audience":null},{"path":"aws-0-eu-central-1.pooler.supabase.com;postgres","kind":"PostgreSQL","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"PostgreSQL\",\"path\":\"aws-0-eu-central-1.pooler.supabase.com;postgres\"}","audience":null},{"path":"https://www.dataaccess.com/webservicesserver/numberconversion.wso","kind":"Web","provider":"CdsA","authenticationKind":null,"environmentName":null,"apiName":null,"connectionName":"{\"kind\":\"Web\",\"path\":\"https://www.dataaccess.com/webservicesserver/numberconversion.wso\"}","audience":null}]},"annotations":[{"name":"pbi:QueryGroups","value":"[{\"id\":\"ae5fc2e2-0e35-4744-846d-c4964261e147\",\"name\":\"Data types\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"e254aa64-c995-446f-a00b-3725fa9d53c5\",\"name\":\"Data Transformation\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"2e3ca2c1-91bc-4dd5-9b0d-ff6ea8fd4e57\",\"name\":\"Schema changes\",\"description\":\"\",\"parentId\":null,\"order\":1},{\"id\":\"efa7e860-7e33-496b-b3ff-433cfe7a6e3f\",\"name\":\"Joins\",\"description\":\"\",\"parentId\":null,\"order\":0},{\"id\":\"87457bf0-ac2e-482e-948a-5ae1a33e52b7\",\"name\":\"Non scalar data types\",\"description\":\"\",\"parentId\":null,\"order\":0}]"}],"entities":[{"$type":"LocalEntity","name":"Type casting","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Type%20casting.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"INTEGER_AS_VARCHAR","dataType":"string"},{"name":"DATE_AS_VARCHAR","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-15T20:02:09.1882285+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Type%2520casting.csv?snapshot=2024-04-15T20%3A02%3A09.1973006Z"}]},{"$type":"LocalEntity","name":"Delimiter separated values","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Delimiter%20separated%20values.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"DELIMITER_SEPARATED_VALUES","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-15T20:02:40.3813006+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Delimiter%2520separated%2520values.csv?snapshot=2024-04-15T20%3A02%3A40.3974573Z"}]},{"$type":"LocalEntity","name":"Schema changes","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Schema%20changes.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"Attribute","dataType":"string"},{"name":"Value","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-15T20:03:11.2288482+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Schema%2520changes.csv?snapshot=2024-04-15T20%3A03%3A11.2348218Z"}]},{"$type":"LocalEntity","name":"Left table","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Left%20table.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"REFERENCE__JOIN_LEFT_TABLE","dataType":"int64"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-15T20:03:41.8545599+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Left%2520table.csv?snapshot=2024-04-15T20%3A03%3A41.8613078Z"}]},{"$type":"LocalEntity","name":"Right table","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Right%20table.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"LABEL","dataType":"string"}],"partitions":[{"name":"Part001","refreshTime":"2024-04-15T20:04:12.3115182+00:00","location":"https://wabiweubpcdsap1.blob.core.windows.net:443/25d1bdf4-0420-4696-8bb3-09226db0b699/Right%2520table.csv?snapshot=2024-04-15T20%3A04%3A12.3168877Z"}]},{"$type":"LocalEntity","name":"Non scalar power query types","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Non%20scalar%20power%20query%20types.csv"},"attributes":[{"name":"ID","dataType":"int64"},{"name":"JSON_TYPE","dataType":"string"}]}]}